version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: jdbcDatabase
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jbdc
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "4000:3306"
    volumes:
      - mysql_jdbc_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
volumes:
  mysql_jdbc_data: